# Generated by Django 2.1.8 on 2019-12-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teachher',
            new_name='teacher',
        ),
    ]
