# Generated by Django 2.1.8 on 2019-12-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191216_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursetag',
            options={'verbose_name': '课程标签', 'verbose_name_plural': '课程标签'},
        ),
    ]
