# Generated by Django 2.1.8 on 2019-12-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='', max_length=500, verbose_name='视频属性名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500, verbose_name='视频名'),
        ),
    ]
