# Generated by Django 2.1.8 on 2019-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='', upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
